just added few times and changes to be made
volhacks/volhacks.github.io pull request #103
Opened 2021-09-22 23:24 UTC by Manan-dev

Don't approve this until we have everything finalized, just put it here so i can work on other stuff

2021-09-24 15:42 UTC, andreicozma1 requested changes

2021-09-24 15:42 UTC, andreicozma1 commented on index.html
>                  <td class="right">TBA</td>
Could we add the finalized times for meals from Franklin?

2021-09-24 15:42 UTC, andreicozma1 commented on index.html
>                  <td class="right">12 AM</td>
Convert all times to the same format for consistency, like 12:00AM if minutes are missing from any

2021-09-24 15:42 UTC, andreicozma1 commented on index.html
> +                <td class="right">3:00 PM</td>
What should we do about the other sponsor tech talks times? For Saturday should we add the other available times as well even tho not all may be filled out?

2021-09-24 15:44 UTC, andreicozma1 commented
Let's finish these up at the meeting as priority and have the second one as lesser priority @Manan-dev 
CC: @hunterprice04

2021-09-25 01:41 UTC, Manan-dev commented
Let me know what else I should add to schedule.

2021-09-25 01:48 UTC, andreicozma1 approved these changes
Just the change mentioned above, otherwise everything looks great!

2021-09-25 01:48 UTC, andreicozma1 commented on index.html
> +                <td class="middle">Room 435</td>
Remove room numbers from tech talks for now as we still gotta confirm those 100%, as of now they are tentative but for the public let's keep TBA

2021-09-25 01:49 UTC, andreicozma1 requested changes
Just change mentioned above, otherwise everything looks great!

2021-09-28 21:59 UTC, andreicozma1 approved these changes

2021-09-28 22:57 UTC, merged